### ISSUE TITLE
Update metadata fields of CSV

### ISSUE THREAD

**Issue by andreasgerstmayr** [grafana/tempo-operator#444]
```[tasklist]
### Tasks
- [x] create metadata.annotations.description 1-liner description about the operator
- [x] list operator features in the spec.description field
- [x] add link to spec.description where to find more information about tempo
- [x] add potential pre-requisites for using the operator in the description field (object storage)
- [x] "TempoStack is the Schema for the tempostacks API." -> "TempoStack is the spec for Tempo deployments."
- [x] Both community operators should be provided by "Grafana Tempo SIG Operator"
- [x] Update support field from "Tempo Operator SIG" to "Grafana Tempo SIG Operator"
- [ ] update keywords
```
