### ISSUE TITLE
Support Tempo deployments in monolithic mode

### ISSUE THREAD

**Issue by andreasgerstmayr** [grafana/tempo-operator#710]
The operator should support Tempo deployments in [monolithic mode](https://grafana.com/docs/tempo/latest/setup/deployment/#monolithic-mode).
For example local filesystem and in-memory storage is only available in monolithic deployments.

Design doc: https://docs.google.com/document/d/1fbBfXddfukj6Pfkr8rtRfUj522pIk5JKBzA_WyppPW0

```[tasklist]
### Tasks
- [x] In-memory storage: #722
- [x] PV storage: #722
- [x] Object storage: #763
- [x] Ingestion OTLP/gRPC: #722
- [x] Ingestion OTLP/HTTP: #722
- [x] Ingestion TLS: #756
- [x] Jaeger UI: #722
- [x] Jaeger UI Ingress+Route: #755
- [x] Multitenancy/Gateway: #816
- [x] Observability: ServiceMonitor, PrometheusRules, GrafanaDatasource: #793
- [x] Overlay config: #722
- [x] Management State: #722
- [x] Resources/Limits: #771
- [x] Operand status field: #787
- [x] Upgrade: #850
- [x] Tolerations (#782)
- [x] support custom service account: #836
- [x] TLS Profile: #862
- [ ] watch external resources (storage secret, T config map and secret)
```

**Comment by pavolloffay** [comment]
Closing as done
